name: XzeelCore
version: '1.2025.1'
main: org.xzeelketche.xzeelcore.XzeelCore
api-version: '1.21'
load: STARTUP
authors: [ XzeelKetche, Envy Studio ]
description: An original XzeelCore plugin.
website: https://xzeelketche.carrd.co/
commands:
  help:
    description: Show the help menu.
    usage: /help
    permission: xzeelcore.help
  xzeelcoreupdate:
    description: Check for plugin updates.
    usage: /xzeelcoreupdate
    permission: xzeelcore.update
    permission-message: You don't have permission!
permissions:
  xzeelcore.help:
    description: Allows use of the help command.
    default: true
  xzeelcore.update:
    description: Allows use of the xzeelcoreupdate command.
    default: op